### ISSUE TITLE
No internet connection on app

### ISSUE THREAD

**Issue by sh3ll4rpw** [nighthawk-apps/nighthawk-android-wallet#63]
I'm using Orbot, with different android devices and versions I have no internet connection on Nighthawk anymore. I didn't update for a year but all was ok. I got the newest nighthawk version now and the issue is still there. When I try to change server I get some java communication error

**Comment by nighthawk24** [comment]
Visit https://lightwalletd.com/posts/june2024 to read the latest post and on how it might affect your use of the services.
