### ISSUE TITLE
qrcodes in the format `zcash:<address>?amount=<amount>` are not recongized

### ISSUE THREAD

**Issue by joga84** [nighthawk-apps/nighthawk-android-wallet#67]
### Describe the issue

Trying to scan the qr code for payment in the common format:

`zcash:<address>?amount=<amount>`

fails.

### Can you reliably reproduce the issue?
1.  create qr code in the format `zcash:<address>?amount=<amount>`
2.  try to scan with nighthawk
3.  nighthawk says in invalid address

### Expected behavior

qr codes in the format `zcash:<address>?amount=<amount>` should be supported

### Actual behavior + errors

qr codes in the format `zcash:<address>?amount=<amount>` fail to scan at all not even the address part gets parsed.

- App Version: 2.2.14
- Android Version:  14

**Comment by nighthawk24** [comment]
Fixed with v2.2.15
